/* ------------------------------------------------------------------ */
/*  PARTICLEX + EVOLVE MED — image corpus manifest                     */
/*  One poetic subject per image. Every subject is distinct, concrete  */
/*  and text-free (the render style enforces "no text, no letters").   */
/*  8 ParticleX scopes × 100 subjects + 4 Evolve Med vectors × 16.     */
/* ------------------------------------------------------------------ */

export const CATEGORY_LABELS = {
  formulas: "Reality Formulas",
  perception: "Perception Fields",
  emotions: "The Making of Emotions",
  belief: "Belief Systems",
  quantum: "Quantum Reality",
  parallel: "Parallel Formulas",
  mycelia: "The Mycelial Origin",
  vibration: "Vibration & Monuments",
  genome: "The DNA & Synthetic Genomics Layer",
  engines: "The Core Therapeutic Engines",
  medworld: "The Global Med-World",
  interface: "The Meta-Biological Interface",
};

export const CATEGORY_ORDER = Object.keys(CATEGORY_LABELS);

const subjects = {
  /* ---------------- formulas · Reality Formulas ------------------- */
  formulas: [
    "a colossal balance scale weighing a star against a single drop of dew",
    "a vast orrery of brass planets locked in perfect gear ratios",
    "a pendulum swinging between two moons and tracing silver arcs of fate",
    "a loom weaving the threads of a destiny into the fabric of a landscape",
    "a river forking into symmetric branches, each branch a life not lived",
    "a great marble staircase spiraling around a suspended sphere of light",
    "a gardener pruning a topiary that grows along a perfect logarithmic spiral",
    "an hourglass whose falling grains settle into tiny constellations",
    "a cathedral of interlocking rings rotating around a silent core",
    "a bridge of chained arcs spanning a canyon, each arc smaller than the last",
    "a giant astrolabe held by stone hands at the edge of the sea",
    "a field of sunflowers all bowing at the same exact angle",
    "a tree whose branches split in perfect binary forks against the sky",
    "a set of nested cups of light, each holding a smaller universe",
    "a mason fitting a keystone into an arch of suspended stones",
    "a carousel of orbiting moons circling a sleeping giant",
    "a candle flame bending into a perfect parabola above a wick",
    "a lighthouse beam sweeping across a sea of floating compass needles",
    "a beehive whose hexagonal cells each hold a tiny frozen moment",
    "a mill wheel turning a river into silver threads of light",
    "a weaver's shuttle carrying a thread through a warp of moonbeams",
    "a suspension bridge's cables forming a perfect catenary curve over a sleeping town",
    "a chessboard carved from a cliff, its pieces frozen mid-leap in ordered jumps",
    "a spiral of stepping stones rising from a misty lake toward a door in the clouds",
    "a glassblower shaping a sphere of swirling weather",
    "a metronome the size of a mountain ticking above a quiet city",
    "a flock of starlings folding into a single rotating torus at dusk",
    "a potter's wheel spinning clay into a perfectly regular amphora",
    "a waterfall pouring through a ring of standing arches, each ring lower",
    "an ancient library where books orbit the shelves like moons",
    "a lone sailor following a wake that curls into a Fibonacci coil",
    "a giant compass drawing a circle around a sleeping island",
    "an orchard where every tree leans along the same invisible gradient",
    "a set of Russian dolls, the smallest holding a spark of dawn light",
    "an orrery hall where scholars' long shadows measure planetary arcs",
    "a lantern maker bending ribs of whalebone into perfect ellipses",
    "a spider's web strung between two mountain peaks, dewdrops at equal intervals",
    "a cloud of butterflies arranging itself into a perfect double spiral",
    "a great mill of the heavens grinding starlight into seasons",
    "a monk gardener raking ever-larger circles into a sand garden",
    "a mechanical nightingale assembling itself from smaller singing birds",
    "a staircase of floating stone slabs rising in strict perspective to a single star",
    "a river delta fanning into identical silver channels toward the sea",
    "an eclipse machine of brass rings aligning sun and moon over a kneeling crowd",
    "a plain of windmills with every blade caught at the same angle of turn",
    "a pair of scissor-hands cutting a ribbon of dawn into equal days",
    "a maker's bench where tiny clocks are born from a spring of light",
    "a greenhouse of glass flowers growing along trellises of pure geometry",
    "a raft of paper boats drifting in perfectly spaced parallel lines",
    "a stone cutter splitting a marble block along an invisible perfect plane",
    "a baker pulling dough into strands that braid themselves mid-air",
    "a harbor of mirrored lighthouses each flashing in strict sequence",
    "a weathervane rooster turning an entire town's shadows at once",
    "a mountain monastery whose prayer flags hang at mathematically equal intervals",
    "a chess knight carved from meteorite leaping an infinite board",
    "a great hour hand rising from the sea to touch the zenith",
    "a salt flat mirroring the sky so precisely that both become one formula",
    "an amphitheater of concentric terraces facing a single floating cube",
    "a glass pyramid refracting one beam into seven ordered rivers of light",
    "a card catalog whose drawers open onto tiny moving dioramas",
    "a ferryman poling a boat along a canal that loops into a perfect knot",
    "a field of standing mirrors angled to send one sunbeam around the world",
    "an astronomer's desk where a brass sun revolves around a paper moon",
    "a vine trellis grown into the exact curve of a suspension cable",
    "a slow tortoise walking a line of stepping stones each spaced to its stride",
    "a blacksmith hammering a horseshoe whose curve matches a planet's orbit",
    "a glazier assembling a rose window whose petals interlock like gears",
    "a flight of paper cranes ascending in a precise double helix",
    "a watchmaker placing a final gear the size of a sun into the sky",
    "a puppeteer's strings descending from the clouds, lifting a dancing bear",
    "a canal lock raising a boat one measured step at a time",
    "a field of dominoes toppling in a great sweeping spiral across a desert",
    "an alchemist's balance with a feather on one pan and a mountain on the other",
    "a caravan of camels crossing dunes with perfectly symmetrical crests",
    "a chess clock with two faces, one running forward, one backward",
    "a gardener espaliering a pear tree into a fan of perfect rays",
    "a pair of scales where the weights are tiny moons and feathers",
    "a giant nautilus shell half-buried in sand, its chambers glowing faintly",
    "a flock of geese closing their V into a single arrow of light",
    "a drawbridge lowering across a moat of stars in measured increments",
    "a miller pouring grain that lands in rows of equal spacing",
    "a spiral galaxy seen edge-on through an antique brass telescope on a hill",
    "a sequence of street arches, each arch exactly one stone wider",
    "a kite train of ten kites rising at equal intervals into dawn",
    "a potter measuring a vase against a feather to the width of a hair",
    "a bamboo grove whose culms stand in perfect Fibonacci spacing",
    "a fleet of paper lanterns ascending in even, unhurried ranks",
    "an hourglass the size of a church, sand falling into a model valley",
    "a weaver's loom where the warp is rain and the weft is sunlight",
    "a cartographer drawing coastline after coastline, each one repeating the first",
    "a giant spring uncoiling from a mountaintop into a spiral railway",
    "a flock of sheep moving through a gate in strict single file",
    "a lantern-lit study where a brass beetle walks a track of brass gears",
    "a double staircase where two dancers mirror each other exactly",
    "a tidal pool at dawn holding a miniature of the whole bay",
    "a stone balanced impossibly on a single grain of sand by a patient monk",
    "a great wheel of fortune turned by tiny angels pulling on braided ropes",
    "a sundial the size of a plaza casting a shadow that points to one door",
    "a tree of nested rings, each ring a year, each year a smaller tree",
    "a sleeping giant whose breath moves the tides in and out on schedule",
  ],

  /* ---------------- perception · Perception Fields ---------------- */
  perception: [
    "the world through a bee's eyes: a garden exploding into hexagonal panels of ultraviolet light",
    "the world through a cat's senses: a dim room lit by rivers of moving warmth",
    "the world through an oak's slow gaze: a century of seasons circling one meadow",
    "the world through a whale's song: the ocean drawn as vast nested spheres of sound",
    "the world through an eagle's eyes: a valley mapped in a thousand sharpest details",
    "the world through moss: a forest floor as a landscape of soft green mountains",
    "the world through a bat's echo: a cave carved anew each instant by rings of sound",
    "the world through a moth: a candle flame as a beacon tower in the dark",
    "the world through a snake's pits: a mouse glowing as a sun of warmth in cool grass",
    "the world through a shark: the sea laced with the heartbeat trails of hidden fish",
    "the world through a dolphin: a shipwreck revealed as a sculpture of returning clicks",
    "the world through a spider: a garden as a vibrating web of weighted threads",
    "the world through a firefly: a summer night as a language of rising sparks",
    "the world through a dragonfly: a pond where every future flight path glows at once",
    "the world through a hummingbird: a flower as a landing platform of liquid light",
    "the world through a wolf: a snowfield stitched with the fading threads of scent",
    "the world through an elephant: a savanna trembling with distant footfalls of rain",
    "the world through a raven: a field where every shiny thing rings like a bell",
    "the world through an octopus: a reef rendered in shifting skins of polarized light",
    "the world through a chameleon: a branch seen twice at once, each eye its own sun",
    "the world through a butterfly: a meadow as a map of landing pads tasting of sky",
    "the world through a hawk: a mouse-hole a mile below appearing as wide as a doorway",
    "the world through a mole: a tunnel system as a warm cathedral of touch",
    "the world through a cavefish: absolute darkness given shape by gentle pressure waves",
    "the world through a salmon: a river remembered as a single magnetic road home",
    "the world through an ant: a forest floor as an endless plain of scented landmarks",
    "the world through a cricket: a meadow evening measured in the temperature of song",
    "the world through a frog: a pond surface as a dome of floating jewel-like targets",
    "the world through a turtle: the sea as a slow rotating compass of light and current",
    "the world through a fox: a winter hedge hollowed into a den of quiet warmth",
    "the world through a deer: a meadow's edge as a cathedral of trembling silences",
    "the world through a bear: a river from beneath, salmon crossing like bright comets",
    "the world through a penguin: the ice as a sky and the sky as a deep cold sea",
    "the world through an albatross: an ocean shrunk to a single winding air-current road",
    "the world through a jellyfish: the deep sea as a slow pulse of moonlight",
    "the world through a starfish: a tide pool as a center of five radiating worlds",
    "the world through a snail: a garden wall as a continent crossed in one summer",
    "the world through an earthworm: the soil as a dark, endless, nourishing sky",
    "the world through a beetle: a desert of grains, each one a boulder of crystal",
    "the world through a grasshopper: a field as a symphony of measured leaps",
    "the world through a seagull: a harbor as a wheel of moving crumbs and currents",
    "the world through a pelican: the sea as a shallow mirror full of silver shadows",
    "the world through a heron: a marsh as a still mirror with one trembling fish",
    "the world through a barn owl: a night field as a whispering map of small hearts",
    "the world through a bloodhound: a city street as a braided river of every passerby",
    "the world through a horse: an open plain as a horizon that calls to run",
    "the world through a cow: a pasture as a slow rhythm of grass, shade and herd",
    "the world through a goat: a cliff face as a staircase of delicious ledges",
    "the world through a sheep: a hillside as a moving ocean of wool and wind",
    "the world through a bee colony: a hive's shared mind as one hexagonal sun",
    "the world through an ant colony: a superorganism feeling the forest as one body",
    "the world through a coral reef: the water as a single slow-thinking jewel",
    "the world through plankton: the midnight sea as a snowfall of edible stars",
    "the world through a tardigrade: a droplet of moss water as a boundless cosmos",
    "the world through a dandelion: a meadow as a launching field of waiting winds",
    "the world through a sunflower: a whole day as one long, slow golden turning",
    "the world through a vine: a wall as a lattice of remembered holds and sun",
    "the world through a lotus: a pond as a ceiling of light descending",
    "the world through a cactus: a desert as one long patient counting of rare rains",
    "the world through a redwood: a forest as a columnar cathedral of climbing light",
    "the world through a lichen: bare rock as a slow feast unfolding over centuries",
    "the world through a kelp forest: the canopy as a swaying green sky above a fish street",
    "the world through a mountain: geology as one slow thought turning to stone",
    "the world through a river: the valley as one long unbroken journey finding the sea",
    "the world through a glacier: a valley as a slow, crushing embrace of ice",
    "the world through a volcano: the crust as a thin skin over a sea of light",
    "the world through the moon: the earth as a face of changing weather and tides",
    "the world through a cloud: the land as a moving shadow theater of rain",
    "the world through a desert: the sky as a great wheel of thirst and stars",
    "the world through a lighthouse: the night sea as a field of passing ships' hearts",
    "the world through an old lighthouse keeper: the horizon as a held breath between lights",
    "the world through a child: a backyard as a continent of giants and tiny empires",
    "the world through a blind musician: a room as a sphere of returning warmth and sound",
    "the world through a sailor: the ocean as a chart of swells read by the keel",
    "the world through a shepherd: a hillside as one moving flock and one loyal dog",
    "the world through a midwife: a home as a quiet tide of arriving life",
    "the world through a beekeeper: a hive as a humming town of golden streets",
    "the world through a diver: the reef wall as a falling canyon of colored light",
    "the world through a stargazer: the night sky as a dome of slow silver wheels",
    "the world through a farmer: a field as a circle of seasons walking hand in hand",
    "the world through a migrating bird: the earth as one vast winding corridor of warmth",
    "the world through a monarch butterfly: a continent as a chain of milkweed islands",
    "the world through a sea turtle: the open ocean as a nursery of drifting moons",
    "the world through a swallow: the summer air as a dome of darting insect stars",
    "the world through a sparrow: a hedgerow as an entire nation of seeds and perches",
    "the world through a hedgehog: a garden as a night pantry of scents and slugs",
    "the world through an otter: a river as an endless water-slide of silver play",
    "the world through a beaver: a stream as a pond waiting patiently to be built",
    "the world through a raccoon: a night town as a constellation of unfastened lids",
    "the world through a camel: a desert as a long memory of distant green horizons",
    "the world through a sled dog: the arctic night as a ribbon of running light",
    "the world through a carrier pigeon: the sky as a single taut thread toward home",
    "the world through a silkworm: a mulberry leaf as an endless white country",
    "the world through a honeybee at dusk: the last flowers as slow closing lanterns",
    "the world through a mayfly: one long golden afternoon as an entire lifetime",
    "the world through a tortoise: a century of the same garden, slowly rearranged",
    "the world through an old dog asleep: a house as a circle of familiar footsteps and sun",
    "the world through a newborn foal: a meadow as an impossible standing ocean of grass",
    "the world through a mountain goat kid: cliffs as a playground of balanced stones",
    "the world through the last whale singing: an empty ocean crossed by one surviving song",
  ],

  /* ---------------- emotions · The Making of Emotions ------------- */
  emotions: [
    "a vast underground foundry where small glowing hearts are hammered into being",
    "a crucible pouring molten golden light into a mould shaped like a teardrop",
    "a bellows breathing slow fire beneath a floor of sleeping houses",
    "a glassblower shaping a glowing orb of feeling at the end of a long pipe",
    "a weaver at a loom turning threads of memory into a cloth of feeling",
    "an alchemist's shelf of vessels, each holding a different weather of the soul",
    "a forge where sparks of joy leap upward and settle into constellations",
    "a giant heart-shaped valve room with pipes of warm light running in all directions",
    "a quiet assembly line of hands placing small lights into clay lanterns",
    "a subterranean lake where feelings float like bioluminescent jellyfish",
    "a smithy where a giant anvil rings a first feeling out into the dark",
    "a kiln full of small porcelain hearts cooling in ordered rows",
    "a great hourglass in which sand becomes slowly rising embers",
    "a library of sealed jars, each one holding a preserved thunderstorm",
    "a choir loft where notes fall as visible petals onto a stone floor",
    "a foundry crane lowering a molten sun into a waiting iron chest",
    "a candle workshop where wicks are cut from locks of combed moonlight",
    "a distillery of slow drops, each drop a different shade of longing",
    "a bellows room where apprentices pump tides into a sleeping giant's chest",
    "a garden greenhouse where feelings ripen like fruit on copper vines",
    "a watchtower where a keeper bottles the day's last light for winter",
    "a printing press stamping soft round seals of wax onto the air",
    "a chain of buckets passing light hand over hand up from a deep well",
    "a loom room where unfinished sorrows hang like half-woven tapestries",
    "a foundry floor strewn with failed hearts, each still faintly glowing",
    "a ladder descending into a chest cavity where tiny workers tend fires",
    "a carousel of bottled feelings turning slowly beneath glass domes",
    "a pigeon loft releasing small birds that carry lanterns into the night",
    "a stable where young dragons are raised on measured spoonfuls of courage",
    "a bakery where loaves of warmth are pulled from a stone oven at dawn",
    "a workshop where leather wings are stretched and sung into shape",
    "a lighthouse interior where the lamp is a slowly turning human heart",
    "a blacksmith quenching a red-hot ring of laughter in a barrel of night",
    "a sorting room where falling feathers are weighed against small stones",
    "a greenhouse furnace tended by a gardener with smoke-colored gloves",
    "a music room where a piano releases a flock of small luminous birds",
    "a wind farm of tiny turbines harvesting the breath before a confession",
    "a moonlit laundry line where hung sheets are inflated by passing sighs",
    "a foundry tram carrying a glowing heart along rails through a dark town",
    "a sculptor carving a block of cloud into the shape of an embrace",
    "a tidal mill whose wheel turns only on the pull of distant loved ones",
    "an aviary where captive storms are fed and gently calmed by keepers",
    "a staircase inside a violin, climbing from the waist to the scroll",
    "a cellar of sleeping thunder, each barrel banded with copper promises",
    "a glasshouse where a single tear is grown into a chandelier over years",
    "a rope bridge woven from unsent letters and strong silk",
    "a smith tinning the inside of a great copper heart before the fire is lit",
    "a puppet theater behind whose curtain tiny lights are stitched to strings",
    "a rooftop of brass funnels and copper pans collecting a meteor shower",
    "a diving bell lowering a lantern into the sea of a sleeping mind",
    "an observatory where astronomers catalogue new colors of missing someone",
    "an apothecary shelf of tiny drawers, each humming at a different warmth",
    "a spinning wheel turning raw dusk into thread after thread of calm",
    "a weighbridge where caravans of feeling are measured crossing into a city",
    "a bathhouse of steam where strangers leave their heaviness on the benches",
    "a chimney sweep brushing soot from the flues of a city's collected hearts",
    "a foundry mold split open to reveal a heart still steaming in the dawn",
    "a greenhouse of thunderclouds tended in pots and pruned with long shears",
    "a knot-tying school where sailors learn to fasten feelings to masts",
    "a candle-lit anatomy theater where the heart is shown as a small sun",
    "a wind-up music box the size of a chapel, playing one held chord of longing",
    "a terracotta army of small figures, each holding its own lantern of grief",
    "a canal barge loaded with sealed amphorae of slowly cooling anger",
    "a stage where a dancer's leap leaves a visible trail of golden dust",
    "a lockkeeper's cottage where feelings are raised and lowered between waters",
    "a quarry where blocks of quiet are cut for building inner walls",
    "a great loom of whalebone weaving winter coats from accumulated tenderness",
    "a chemist's bench where two clear liquids meet and bloom into rose light",
    "a paper mill turning rags of old sorrow into fresh blank pages of morning",
    "a foundry whistle ending the shift of ten thousand small hearth-fires",
    "a seed vault where first-love is stored in folded paper envelopes",
    "a bridge tender opening a span to let a river of longing pass beneath",
    "a dovecote releasing birds at dusk, each carrying a coal of memory",
    "a wall of coat hooks where travelers hang their invisible burdens",
    "a brewer stirring a copper kettle that fogs the windows with homesickness",
    "a storm-warning station hoisting flags of amber calm along a cliff",
    "a file room where echoes of old laughter are kept in matchboxes",
    "a glass harmonica played by breath instead of fingers, rings of light rising",
    "a mason repointing the mortar of a heart-shaped garden wall",
    "a lamplighter on a ladder touching flame to the wicks of a dark avenue",
    "a tinker's cart mending kettles, bells and small broken tempers",
    "a night watchman carrying a lantern among sleeping peppers and pale moons",
    "a fountain whose basin catches coins of wishes and returns them as mist",
    "a foundry apprentice asleep on a bench, dreams leaking as small sparks",
    "a team of plumbers fitting pipes to a house whose water is pure feeling",
    "a carousel horse mid-gallop shedding painted stars from its mane",
    "a knot garden hedge clipped into the shape of a held breath",
    "a ferry crossing a black lake, its single lantern doubled in the water",
    "a clockmaker oiling the escapement of a heart so it beats a moment longer",
    "a theater fly loft where painted clouds are lowered onto a sleeping stage",
    "a conservatory palm bending toward the only window with light left",
    "a key-cutter grinding a small brass key that opens no door yet",
    "a choir of stone gargoyles rehearsing a dawn chorus in an empty cathedral",
    "a smith welding two halves of a broken compass back into one circle",
    "a hot air balloon sewn from patchwork pieces of remembered summers",
    "a well sweep dipping its bucket into a well of warm darkness",
    "a night telegraph office where the keys click comfort into the dark",
    "a gardener grafting a branch of apple blossom onto an old gnarled grief",
    "a chandler dipping candles that will burn only with borrowed courage",
    "a foundry gate closing at dusk, its furnace heart still glowing through the seams",
  ],

  /* ---------------- belief · Belief Systems ----------------------- */
  belief: [
    "a colossal invisible engine revealed only by the steam rising from a town",
    "a cathedral nave whose pillars are being voted into place by rising hands",
    "a giant ballot urn glowing as countless threads of light flow into it",
    "a palace built on pillars of pure conviction above an abyss of doubt",
    "a prayer wheel the size of a lighthouse turned by an endless river",
    "a floating city held aloft by ten thousand taut threads of shared faith",
    "a machine of stained glass gears turning a sunbeam into a morning",
    "a courtroom where the jury are stone statues slowly nodding",
    "a bridge assembling itself plank by plank ahead of a walking crowd",
    "a great candle whose flame bends toward the largest gathering of believers",
    "a loom weaving a road out of promises and colored silks",
    "a war room where maps lift off the table and become the land itself",
    "a silent colosseum where an invisible chariot races around the rim",
    "a giant hand pulling a rope that raises the sun over a hill village",
    "a temple bell with no clapper that rings only when two strangers agree",
    "an aqueduct carrying conviction from the mountains into a thirsty city",
    "a warehouse of beliefs stacked like crates, some leaking faint light",
    "a town square where every fountain flows upward toward a shared idea",
    "a printing house where presses stamp crests onto the wings of doves",
    "a beacon chain of hilltop fires lit in one unanimous breath",
    "a puppeteer's booth above a village, strings descending into every chimney",
    "a giant keyhole in a mountain with a queue of pilgrims holding keys",
    "a market where ideas are traded as birds in open cages",
    "a courthouse scale weighing a feather of hope against an anvil of fear",
    "a great organ whose pipes are the chimneys of every hearth in a valley",
    "an orchard where each tree bears fruit shaped like the wish of its planter",
    "a bridge of handprints cast in bronze spanning a gorge",
    "a colossus of a kneeling figure whose shoulders carry a highway of pilgrims",
    "a giant loom upstairs in a farmhouse, quietly weaving tomorrow's weather",
    "a train whose locomotive is a lantern pushed by a crowd of shadows",
    "a lighthouse whose beam exists only because sailors keep rowing toward it",
    "a fortress wall built overnight from stones that were only pebbles at dusk",
    "an auction house selling bottled courage to the highest bidders",
    "a monorail of hanging lanterns strung between distant temple roofs",
    "a collective loom where a whole village knits one enormous scarf of resolve",
    "a courtroom where the verdict is a door that opens into different weather",
    "a granary storing harvests that have not yet been planted",
    "a relay of mirror towers passing one identical idea down a coastline",
    "a belfry from which thousands of paper birds spiral over a city",
    "a fountain of coins where every wish sinks and sends up a ring of light",
    "a giant clock whose hands are moved by queues of pushing citizens",
    "an embassy of small houses where neighboring weathers sign treaties",
    "a railway tunnel dug through a mountain of collective certainty",
    "a theater where the audience's breathing raises the curtain by itself",
    "a greenhouse where fragile ideas are grown into hardwood bridges",
    "a pier extending into fog, built nightly by those who believe in the far shore",
    "a wind organ on a cliff playing only when a whole village agrees to listen",
    "a market square where one shared umbrella covers ten thousand strangers",
    "a ship whose hull is caulked with prayers and sealed with wax",
    "a factory stamping out identical brass sunrises for tomorrow",
    "a census office counting the living, the remembered and the hoped-for",
    "a giant loom weaving a flag so large it becomes the sky over a nation",
    "a signal box switching the rails of a town's collective morning",
    "a candlelit scriptorium where what is imagined becomes weather outside",
    "a vault whose door opens only to a chorus of voices in unison",
    "a lighthouse keeper refilling the lamp with bottled community spirit",
    "a procession carrying a single enormous key toward a door in the air",
    "a quarry where doubt is cut into building blocks and sold cheaply",
    "a greenhouse dome over a sleeping seed the size of a cathedral",
    "a ferryman who asks no fare, only that passengers believe in the far bank",
    "a theater of shadows where the wall is voted brighter each night",
    "a drawbridge of woven scarves lowering for an army of schoolchildren",
    "a great weighbridge where a town's shared load is balanced against dawn",
    "a monument of interlocked hands so tall it leans on the clouds",
    "a pigeon loft where every bird flies home to a different imagined city",
    "an engine room where stokers shovel bottled applause into the boilers",
    "a hilltop ziggurat with a queue of lanterns spiraling to the summit",
    "a cartography office drawing coastlines that the sea hurries to fill in",
    "a choir rehearsing in a barn while the barn slowly grows a dome",
    "a bank vault of stored sunrises, withdrawn one per desperate morning",
    "a bridge toll booth where the toll is one honest hope per crossing",
    "an observatory dome that opens only when enough eyes look up together",
    "a giant quill resting on a hillside, having become a cedar forest",
    "a fleet of paper boats launched by one child and followed by a navy of clouds",
    "a great windmill whose sails are ladder rungs for ascending ideas",
    "a courtroom sketch artist drawing a better world until it testifies",
    "a night watchman lighting lamps along a road that does not exist yet",
    "a bell foundry casting one enormous silence shaped like a bell",
    "a harbor where ships are built around their own future figureheads",
    "a postman delivering sealed envelopes of courage door to door",
    "a glassblower inflating a bubble city that hardens into skyline at dawn",
    "a mountain tunnel bored by a drill shaped like a pointed finger",
    "an apiary where hives are stacked into the shape of a cathedral",
    "a great mill wheel turned by the river of a town's collected certainty",
    "a fortress gate that opens for anyone who names it kindly",
    "a planetarium machine at the center of a village, turning the real sky",
    "a forest where trees lean together to form an aisle for a wedding",
    "a ferry of lanterns crossing a river of forgetting, rowed against the current",
    "a greenhouse of frost-tender hopes carried indoors each winter by a whole town",
    "a giant abacus on a hillside whose beads are moved by common consent",
    "a relay team of runners passing a single lit torch around the world",
    "a workshop where wings are fitted to praying figures before dawn",
    "a stone arch left unfinished for a century, completed in one night",
    "a tide mill whose pond fills only with water carried by hand",
    "a seed swap in a market square where fortunes are exchanged as beans",
    "a giant door standing alone in a field, always slightly ajar",
    "a lighthouse built on a rock that floats because the keepers keep rowing",
    "a tower of stacked chairs reaching to heaven, climbed by volunteers",
    "a well so deep the bucket returns filled with starlight and agreement",
    "a city whose bridges exist only where two banks reach out at once",
  ],

  /* ---------------- quantum · Quantum Reality --------------------- */
  quantum: [
    "a cat rendered half in midnight ink and half in daylight, asleep and awake at once",
    "two dice on opposite horizons showing the same face at the same instant",
    "a wave rippling through a pond and passing through both slits of a stone wall at once",
    "a cloud chamber where particle trails bloom like tiny frozen lightning ferns",
    "a cosmic dice cup shaking a universe of stars into a single thrown pattern",
    "a labyrinth of mirrors where a single walker takes every corridor at once",
    "a coin spinning above a fountain, neither face landing, forever suspended",
    "a garden of quantum flowers, each blossom open and closed on the same stem",
    "a bridge of probabilities half-built, its planks fading where no one would cross",
    "a house of mirrors reflecting one lantern into an infinite lattice of twins",
    "a clock with translucent hands sweeping all the hours of the day at once",
    "two entangled moths dancing at opposite ends of a moonlit garden",
    "a sea of foam where each bubble holds a brief universe of smaller waves",
    "a wagon wheel spinning so fast its spokes become a still translucent disc",
    "a staircase where each step exists only while it is being stepped on",
    "a spider web trembling at one corner and shivering at the far corner instantly",
    "a lantern dimming to a mist of maybe-lights inside a mountain cave",
    "a tree of branching paths, every branch bearing the same walking traveler",
    "a pair of gloves knitted from one thread, one warming on the moon",
    "a ship sailing on every possible sea at once, its wakes fanning like a peacock tail",
    "a bell that rings and does not ring inside a sealed glass sphere",
    "a field of standing stones casting shadows in all directions at once",
    "a key that unlocks a door while still turning in the keyhole",
    "a ladder leaning against a wall of pure potential, rungs appearing underfoot",
    "an iceberg whose reflection above and below trade places mid-gaze",
    "a loom weaving a cloth from warp threads that are also weft threads",
    "a lighthouse whose beam splits, illuminates two ships, and reunites brighter",
    "a chessboard where one knight occupies every square in a slow bloom",
    "a weather vane pointing in all directions with equal calm conviction",
    "a snowflake melting and crystallizing in the same warm hand",
    "a tandem bicycle ridden by one rider split into two ghostly riders",
    "a pendulum swinging through the floor of a workshop into the sky above",
    "a pair of scales where the pans hold the same feather and both are heavier",
    "a moon half-waxed and half-waned above a tide that cannot choose",
    "a library where every book is the same book seen from all sides at once",
    "a well whose bucket is drawn up and lowered in the same quiet motion",
    "a corridor of doors where opening one leaves all of them ajar",
    "a compass needle turning to every horizon at once and resting content",
    "a forest path forking endlessly while one pair of footprints walks all branches",
    "a violin string vibrating as a still ribbon of light and a blur at once",
    "a double-exposure dawn where the sun rises on two horizons of the same sea",
    "a paper crane folded and unfolded by the same pair of hovering hands",
    "a windmill whose sails turn clockwise and counterclockwise in the same wind",
    "a lantern in a shipping crate that is packed, shipped and home all at once",
    "a gardener planting a seed that is simultaneously a sapling and a great oak",
    "two telegraph keys on separate islands clicking in the same instant",
    "a flock of starlings forming one bird and a thousand birds in the same sky",
    "a potter's wheel where the clay is simultaneously a vase and the raw earth",
    "a staircase of light reflected through a hall of half-silvered mirrors",
    "a kite flying in a sky that is also the surface of a still lake",
    "a runner on a beach leaving footprints that precede and follow the stride",
    "a seed catalog of impossible apples growing on the same impossible branch",
    "a carousel where every painted horse is the same horse mid-leap",
    "an orrery whose planets orbit every radius at once in translucent shells",
    "a pair of binoculars looking at the same star from two ends of the galaxy",
    "a wagon of fireworks both packed with sparks and blooming overhead",
    "a bell rope pulled in a cathedral on earth, ringing in a cathedral of clouds",
    "a pond frozen at dusk, every ripple still moving beneath the still surface",
    "a moth inside a sealed matchbox, its wings both folded and beating",
    "a deer drinking at a stream, its reflection drinking in the opposite season",
    "a key forged and melted in the same smithy fire, traveling between states",
    "a ladder whose top rung touches the floor of the room above",
    "a wind chime sounding a chord before the wind that stirs it arrives",
    "a rowboat crossing a lake while still tied to the dock by a glowing rope",
    "a greenhouse where frost and bloom share the same pane in perfect stripes",
    "a spinning top carving a still, perfect cone of light on a tabletop",
    "an envelope arriving both sealed and open at the same doorstep",
    "a bridge whose middle stone is dropped into the river by every passerby at once",
    "a lighthouse keeper lighting the lamp and finding it already lit",
    "a pair of dancers mirrored across a hall, touching hands through the floor",
    "a wind-up bird that sings before and after the spring is wound",
    "a train on two parallel tracks at once, its smoke folding into one column",
    "an apple falling upward and downward from the same bent bough",
    "a lantern ship sailing through a sea that is also a night sky",
    "a weaver pulling one thread and ringing two distant bells",
    "a garden gate opening onto spring from the north and autumn from the south",
    "a candle burning at both ends and lasting forever in a mirrored hall",
    "a single drop of rain striking a pond everywhere at once in a silver crown",
    "a boot print on the moon and its twin pressed into wet earth at home",
    "a chandelier of prisms splitting one sunbeam into a choir of walking lights",
    "a ferry that departs and arrives at the same jetty in the same mist",
    "a chess game where every piece returns to its starting square each dawn",
    "a seed pod bursting in slow motion, every seed already a tree in outline",
    "a bell foundry where the cooling bell hums every note it will ever ring",
    "a snow globe shaken once, containing every possible blizzard at once",
    "a cat's cradle of string held between four hands in two different centuries",
    "a mirrored hall of pendulums swinging in impossible sympathy",
    "a lantern glowing brighter when observed and softer when forgotten",
    "a cartographer mapping a coastline that redraws itself behind the pen",
    "a spiral staircase ascending and descending in the same turning step",
    "a butterfly emerging from a chrysalis that is also still a caterpillar",
    "a lantern hung between two hooks, neither of which exists until it is hung",
    "a river flowing uphill and downhill in the same valley of standing stones",
    "a clockmaker fitting a gear that turns both clockwise and through itself",
    "a sailing ship passing through its own reflection without a ripple",
    "a pair of ice skaters drawing one continuous figure on two separate ponds",
    "a bee visiting one flower that blooms in every garden of the town",
    "an orchestra tuning before the concert hall has been built",
    "a single wave frozen mid-curl, holding every drop of the ocean's memory",
    "a lantern-lit workshop beneath the floorboards where tiny gears are still being woven",
  ],

  /* ---------------- parallel · Parallel Formulas ------------------ */
  parallel: [
    "the same copper kettle steaming on twelve different stoves across twelve horizons",
    "a single wooden chair repeated down a long hall of parallel doorways",
    "one lighthouse translated into coral, into ice, into bone and into glass",
    "the same brass key hanging on different hooks in different centuries",
    "a row of parallel harbors where identical boats sail on different-colored seas",
    "one song played on a shell, on a wire, on a gut string, on a blade of grass",
    "the same apple tree bearing pears, plums, stars and clocks in different yards",
    "a staircase of parallel Earths seen edge-on, each with its own rising smoke",
    "the same paper boat crossing ponds, seas, puddles and skies in one image",
    "a carousel of different worlds, each pole painted with the same cup of tea",
    "one bridge repeated as rope, as stone, as root and as rainbow across a gorge",
    "the same bell hung in a tower, on a ship, on a goat and in a garden of glass",
    "a row of identical clocks where each one tells a different kind of noon",
    "the same honey jar in the kitchens of every season at once",
    "one umbrella over parallel rainfalls of water, ash, petals and fireflies",
    "the same wooden door opening onto desert, tundra, ocean and orchard",
    "a spinning wheel in every window of a street that repeats into infinity",
    "the same violin played by a bear, a girl, a machine arm and a willow branch",
    "a shelf of identical teacups, each holding a different small weather",
    "the same sailing ship built from wood, ice, paper and whalebone in dry docks",
    "one campfire burning in a circle of stones on many different moons",
    "the same staircase climbing a lighthouse, a tree, a mountain and a ribcage",
    "a row of windows where the same cat sleeps on different moonsills",
    "the same compass needle pointing to different true norths in a case of worlds",
    "one pair of boots walking on sand, snow, ash, moss and water at once",
    "the same letter copied into twelve hands and sealed with twelve different suns",
    "a foundry casting the same bell in bronze, in glass, in ice and in light",
    "the same waterfall falling into a canyon, a bowl, a cup and an open hand",
    "a garden where the same rose blooms as lily, as starfish and as pinwheel",
    "the same lantern lit in a miner's hand, a diver's hand, a monk's and a child's",
    "one piano heard from twelve open windows of one tall impossible house",
    "the same hourglass running with sand, snow, seeds and slow light",
    "a train station where the same train arrives on tracks of wood, water and cloud",
    "the same kite flown by the same boy on a beach of each different world",
    "a row of parallel wells drawing up water, honey, starlight and small bells",
    "the same greenhouse growing one tomato under twelve kinds of noon",
    "one whale breaching in twelve oceans of different colors at the same moment",
    "the same castle rebuilt as sandcastle, ice castle, driftwood and cloud",
    "a carpenter's bench where the same birdhouse is built from every forest",
    "the same basket carried down twelve market streets, each filled differently",
    "the same moon reflected in twelve puddles along one alley of worlds",
    "a print shop stamping the same swallow onto twelve different skies",
    "the same shovel planted in twelve gardens, each growing a different season",
    "one pair of dancers mirrored on stages of stone, water, cloud and wheat",
    "the same windmill turning on plains of grass, of coral, of dunes and of glass",
    "the same coffee cup resting on books, on moss, on ice and on a drum",
    "a fisherman casting the same line into twelve versions of the same river",
    "the same swing hanging from an oak, a whale rib, a girder and a rainbow",
    "a row of identical chimneys sending up smoke shaped like each inhabitant's dream",
    "the same horseshoe nailed above doors of wood, of bone, of coral and of slate",
    "one candle burning in twelve windows of one lighthouse seen from the sea",
    "the same bicycle leaning on walls in twelve cities of one skyline",
    "the same waterwheel turning in rivers of water, of grain, of light and of song",
    "a botanist pressing the same leaf gathered from twelve parallel forests",
    "the same shepherd's crook held over flocks of sheep and of clouds",
    "one library where the same book rests on shelves in twelve architectures",
    "the same bench beneath twelve different trees in one continuous park",
    "the same globe spun by twelve pairs of hands in one circular study",
    "a harbor of identical rowboats where each seat holds a different occupant's shadow",
    "the same wind-up bird singing in twelve nurseries of one long house",
    "the same fire escape climbing a tenement on twelve different planets",
    "the same sailing knot tied by twelve sailors in one rigging of worlds",
    "the same bench grinder sparking in workshops of wood, brass, ice and coral",
    "the same scarecrow wearing twelve hats in one field of many weathers",
    "the same fountain carved with the same face in twelve plaza mornings",
    "the same pair of spectacles on twelve noses in one floating lecture hall",
    "the same apple falling on twelve desks in twelve studies of one thinker",
    "the same nest built on ledges of cliff, of gargoyle, of crane and of moon",
    "a fleet of identical paper cranes folding themselves in twelve skies",
    "the same bootprint in twelve dusts along one ridge of parallel mountains",
    "the same jar of fireflies lighting twelve porches of one summer night",
    "the same armchair by twelve fires in one long hall of winter worlds",
    "the same church bell heard across valleys of snow, of wheat, of sea and of ash",
    "the same flowerpot on twelve sills of one curved street of windows",
    "the same balloon tied to twelve wrists of one child walking many beaches",
    "the same sawhorse in shipyards building one ship of twelve materials",
    "the same bowl of soup steaming on tables of every continent at once",
    "the same key turning locks of wood, of shell, of frost and of dawn",
    "the same pair of oars rowing twelve boats across one stitched sea",
    "the same milk bottle on twelve doorsteps under twelve different moons",
    "the same ladder against twelve walls of one endless orchard",
    "the same mailbox at the end of twelve gravel roads in one prairie",
    "the same pocket watch opened in twelve lamplights of one traveler",
    "the same heron standing in twelve ponds that mirror one sky",
    "the same straw hat on twelve scarecrows watching over one shared field",
    "the same trumpet on twelve bandstands playing one tune at dusk",
    "the same row of laundry on twelve lines between one repeated alley",
    "the same iron gate opening onto twelve courtyards of one address",
    "the same telescope on twelve balconies aimed at one wandering planet",
    "the same drum beaten at twelve fires of one round horizon",
    "the same staircase spindles turned in twelve workshops of one town",
    "the same crow perched on twelve fence posts of one long field edge",
    "the same watering can tipping over twelve gardens of one terraced hill",
    "the same ring of stones around twelve campfires under one spinning sky",
    "the same beehive smoked by twelve beekeepers of one flowered hillside",
    "the same pair of skis on twelve snows of one repeated mountain",
    "the same bell rope pulled by twelve hands of one congregation of worlds",
    "the same seed packet opened by twelve gardeners of one long spring",
    "the same chalk line snapped across twelve workbenches of one shipyard",
    "the same cup of tea poured in twelve kitchens as one kettle whistles everywhere",
  ],

  /* ---------------- mycelia · The Mycelial Origin ----------------- */
  mycelia: [
    "a vast underground fungal web glowing faintly beneath a sleeping forest",
    "a single spore drifting down from a constellation to land on young stone",
    "a meteorite cracked open on a shore, its core threaded with white filaments",
    "a fairy ring of mushrooms glowing at midnight around a pool of stars",
    "a tree root and a fungal thread shaking hands beneath a cross-section of soil",
    "a fine rain of spores falling upward through a shaft of green light",
    "a forest floor cross-section revealing luminous highways between the trees",
    "a giant bracket fungus on an old oak, shaped like a listening dish",
    "a mushroom city rising in tiers from a mossy ravine at dawn",
    "a bioluminescent grotto where every hanging thread carries a bead of light",
    "a fallen log dissolving into lace as the network drinks it home",
    "a mushroom the size of a temple with pilgrim snails climbing its stem",
    "a root-and-mycelium treaty bound in silver threads across a stone tablet",
    "a puffing mushroom releasing a slow spiral of spores into evening light",
    "an underground lake reflecting a ceiling of woven fungal lace",
    "a spider-web-thin mycelial mat spanning a canyon between two ferns",
    "a cluster of ink-cap mushrooms dissolving into a black pool that mirrors the moon",
    "a glow of foxfire threading the walls of an abandoned root cellar",
    "a fungal chandelier dripping light into a cavern of sleeping bats",
    "a cross-section of earth like a glass farm case, but the galleries glow white-gold",
    "a ring of spores settling in a perfect circle on a mossy boulder",
    "an ancient mushroom casting its shadow over a ring of standing stones",
    "a net of white threads binding a landslide together on a steep hillside",
    "a choir of small mushrooms sprouting in the footprint of a giant",
    "a mycelial web connecting the roots of trees on opposite banks of a stream",
    "a light shower of spores drifting over a glacier's edge and taking root",
    "a great fungal arch bridging two halves of a fallen redwood",
    "a mushroom's gills shown in fine cross-section like the inside of a bell",
    "a network node where ten white threads meet in one knot of brightness",
    "a dew-laden web of mycelium at dawn, every thread strung with beads",
    "a mushroom village with lantern-caps lighting a path through a fern gorge",
    "an old yew whose roots are cradled in a basket of glowing filaments",
    "a slow bloom of mushrooms circling a sleeping fox like a crown",
    "a web of fungal threads vibrating gently as rain taps the soil above",
    "a cross-section of a forest hillside showing the network beneath the snow",
    "a giant morel rising like a cathedral bell in a spring dell",
    "a filament bridge crossing a busy tunnel of burrowing beetles",
    "a mushroom ring around a well that gives water the taste of rain",
    "a constellation of glowing caps on a midnight forest floor like fallen stars",
    "an underground exchange where oak and birch roots pass packets of light",
    "a fruiting body rising from a whale vertebra on a lonely beach",
    "a mycelial tapestry fanned across a cave wall like frozen lace",
    "a spore lantern: a glass sphere where spores orbit like slow fireflies",
    "a cliff of soft loess honeycombed with fungal galleries holding it upright",
    "a young fern unrolling beside a mushroom whose cap shades it like an umbrella",
    "a thread of mycelium crossing a desert inside a dew-heavy buried stone",
    "an old log bridge overgrown into a single living fungal plank",
    "a network of white threads mapping the outline of a buried antler",
    "a mushroom cap collecting rain and dripping it into a waiting fern",
    "a dawn forest where every fallen branch has grown a tiny city of caps",
    "a glowing web pulling nutrients along a thread like beads on a string",
    "a mushroom taller than a deer standing in a shaft of morning mist",
    "an underground river passing through a root-and-fungus colonnade",
    "a fairy ring slowly walking across a meadow over a hundred years",
    "a winter tunnel beneath the snow lined with soft glowing threads",
    "a fungal knot binding a boulder to a hillside like a stitch in cloth",
    "a capless web of threads rippling in answer to a distant footstep",
    "a mushroom grove inside a wrecked ship's hull, sailing silently under moss",
    "a glowing filament mapping the veins of a fallen leaf it is devouring",
    "a ring of mushrooms around a stone where two rivers were married",
    "a spore cloud rising like slow smoke from a cap struck by morning sun",
    "a lattice of white threads holding a handful of forest soil together",
    "an old mushroom with a snail's shell resting on its cap like a helmet",
    "a cavern gallery where stalactites and mycelial threads entwine",
    "a cross-section of a termite mound threaded with cultivated fungus gardens",
    "a web of light threads reaching up to tap the underside of the snowpack",
    "a mushroom growing through a discarded horseshoe like a green crown",
    "an ancient banyan whose aerial roots are knotted with pale filaments",
    "a spore drifting across a young volcano's ash toward the curve of the world",
    "a fungal cord climbing a rope of ivy to raid an abandoned bird's nest",
    "a night marsh where every tussock glows with its private fungal lamp",
    "a giant puffball resting in a clearing like a fallen moon",
    "a root cellar shelf where jars of glowing cultures hum in the dark",
    "a mushroom cap acting as a parasol over a line of marching ants",
    "a web of threads stitching a cracked clay pot back into the garden",
    "a comet of spores arcing over a night forest and showering one glade",
    "an underground council: the roots of nine trees meeting in one bright knot",
    "a fungal lantern grotto where a fox pauses to drink from a glowing pool",
    "a mat of mycelium crossing a glacier's moraine in silver stitched lines",
    "a stack of bracket fungi rising like the shelves of a drowned library",
    "the shadow of a giant cap spread across a meadow as a ring of light",
    "a network thread carrying a bead of water like a courier through the dark",
    "a mushroom orchard planted by hands long gone, still fruiting on schedule",
    "a glowing web tightening around a falling stone, catching it in slow spring",
    "a ring of caps around a hare's form, keeping the frost from its back",
    "a thread bridge carrying two earthworms across a gap in the dark soil",
    "a cross-section of a floating peat island held knit by pale cords",
    "a mushroom cap tilted like a bowl catching the first snow of the year",
    "an ancient stone well rope threaded with white filaments down to the water",
    "a network hub pulsing light toward a sapling newly joined to the forest",
    "a web of filaments strung with morning dew, holding light and nothing else",
    "a fungal stair of shelf fungi climbing a dead trunk like a spiral gallery",
    "a spore wind blowing inland from the sea, seeding a dune with pale threads",
    "an old oak stump crowned in waxcaps, still holding the dawn's gold light",
    "a cross-section of soil like a cathedral nave with thread columns and vaults",
    "a mushroom the color of the moon rising from a crater of dark moss",
    "a web of white cords vibrating like harp strings in the underground wind",
    "a bracket fungus turned into a lamp by a traveler, glowing on a walking staff",
    "a fallen star of light resting in a glade, filaments spreading like roots",
    "the first mushroom on the young world rising to meet the first rain",
  ],

  /* ---------------- vibration · Vibration & Monuments ------------- */
  vibration: [
    "a great pyramid emitting slow concentric rings of stone-hum into the desert night",
    "a standing stone humming with visible ripples spreading across a field of wheat",
    "a stone circle ringing like a struck bell, sound waves drawn as silver rings",
    "a sand pattern blooming on a drumhead as a deep note is held",
    "a tuning fork the size of a tree planted in a garden of rippling water",
    "a cathedral organ whose lowest note makes the candle flames lean together",
    "a temple singing bowl with the water inside rising into perfect geometric peaks",
    "a pyramid's hidden chamber where a granite chest hums a single held note",
    "a cliff face carved as a pipe organ played by the sea swell itself",
    "a choir dome where the chant hangs as visible golden rings beneath the vault",
    "a desert drum circle where the beats travel as rings across the dunes",
    "a row of standing stones each tuned to a different passing cloud",
    "an aeolian harp strung across a canyon, its chords drawn as threads of light",
    "a fountain where water leaps in cymatic crowns above a buried bell",
    "a gong the size of a hilltop struck by the first light of dawn",
    "a megalithic doorway that hums at the exact pitch of the spring thaw",
    "an underground resonance shaft where a dropped pebble rings for a year",
    "a pyramid staircase tuned so each step sounds one lower tone",
    "an ancient two-tone bell with two ripples rising from a single strike",
    "a lighthouse whose lamp pulses in time with the deep heartbeat of the sea",
    "a village well whose bucket rings the water into standing waves",
    "a raindrop striking a still pond and sending rings through a ring of stones",
    "a glass harmonica whirling rings of light above a quiet salon",
    "an obelisk that hums at noon, drawing chalk-dust patterns on the plaza",
    "a quartz crystal the size of a boulder ringing on a bed of moss",
    "a choir of monks holding one note until the dust on the floor arranges into rings",
    "a great bronze age horn laid across a burial mound, still faintly sounding",
    "a plaza of tessellated stone that shivers beneath a street musician's cello",
    "a hanging temple bell moved by no wind, ringing only moonlight",
    "a wave organ built into a harbor wall, played by the tide's slow breath",
    "a salt flat where the wind sets the crust ringing in geometric blooms",
    "a giant resonating gourd buried in a field, humming to the passing herds",
    "a long pyramid causeway that hums under marching feet in steady chords",
    "an echo valley where a single shout returns arranged into ordered harmonics",
    "a stone chime of hanging slabs struck by an oracle's rod at dusk",
    "a suspension bridge whose cables sing in the wind, notes drawn as upright waves",
    "a frozen lake booming in the night cold, ripples drawn beneath the ice",
    "a standing wave of sand held in the air above a desert singing rock",
    "a prayer dome where one held note circles forever along the vault",
    "a carillon tower where every bell casts a ring of its own color of sound",
    "a conch shell on a pillow, its spiral exhaling rings into a dark room",
    "a row of mysterious hollow stones that drone when the tide is high",
    "a chamber of resonant stone where a whisper returns as a chorus",
    "a great pendulum clock whose tick keeps the cathedral masonry humming",
    "a long wooden drone pipe held to the earth, waking circles in the red dust",
    "a glacier calving, its thunder rolling outward as concentric arcs of ice dust",
    "a hummingbird's wingbeat drawn as a halo of standing ripples around a flower",
    "a temple floor of tuned drums played by pilgrims' careful steps",
    "a wineglass rim singing, its liquid standing in cymatic crowns",
    "a bell buoy ringing in fog, its sound drawn as slow rings around the light",
    "a ziggurat with a summit plate that hums to the rising sun",
    "a chalk cliff with flint bands that ring like guitar strings in the gale",
    "an underground cistern where a dropped coin rings forever between vaults",
    "a hanging garden of tuned bamboo pipes chiming in the evening breeze",
    "a pyramid's great chamber as a resonant box, air vibrating in drawn lines",
    "a wineglass caught at the exact moment its note finds itself and shatters",
    "a bullroarer whirling at the end of a cord, drawing a spiral of sound",
    "a rain chain of copper cups each ringing its own note down a temple eave",
    "a great stone gate that hums when the moonlight crosses its lintel",
    "a beehive humming at its own deep pitch, sound drawn as layered hexagons",
    "a ship's figurehead carved as a mouth, singing the waves calm",
    "a belfry at dusk where swallows' wingbeats pluck the silence like strings",
    "a massive iron triangle struck at a mine's entrance, ringing into the mountain",
    "a standing stone tilted to catch the dawn wind like a reed in a flute",
    "a sacred pool holding perfect standing waves inside a ring of votive lamps",
    "a weathered cairn of ringing rocks that resonates when the whole valley is silent",
    "a hollow tree alive with wings, its hum made visible as rising rings",
    "a stone trumpet carved at a cliff mouth, announcing the tide with one long note",
    "a tiered temple roof whose eaves ring with hanging bells at every breath of wind",
    "a meditation hall where one struck bowl keeps every seated figure swaying in time",
    "a resonance pit dug beside a pyramid, a jar humming underground like a hive",
    "a snowfield at night squeaking underfoot in long musical arcs",
    "a great house where every chimney flue sounds a different tone in the gale",
    "an aqueduct where wind over the openings plays a low continuous chord",
    "a stone sun disc on a hill that hums at solstice sunrise",
    "a harbor of bell buoys all ringing in slow tidal unison",
    "a cairn where a single touch sends ripples through the whole pile of stones",
    "a pyramid aligned with a distant bell star, a thread of hum drawn between them",
    "a rain barrel under an eave drumming the storm into rolling rhythms",
    "a long gallery where footsteps become a rising chord of echoes",
    "a camel caravan's bell ringing in a pattern the dunes answer with ripples",
    "a giant marble flute laid on a hillside, its holes aligned to the sunrise",
    "an ice cave where the frozen walls chime with every breath of the sea",
    "a stone rain gong: a basin where drips ring out the hours of a storm",
    "a wooden bridge built as a marimba, every plank a note underfoot",
    "a heavy bronze mirror that hums when it reflects the full moon",
    "a spire of stacked millstones droning in three-part harmony in the wind",
    "a field of tall grass taught by the wind to move in standing waves",
    "a temple drum carved from a single fallen trunk, sounded by the river beneath",
    "a pyramid at dawn with its shadow vibrating like a struck string across the sand",
    "a cave mouth that hums the tide into a village's sleeping ears",
    "a ceremonial gong of meteoric iron kept cool by its own deep note",
    "a stone causeway of hexagonal columns that plays scales as the tide retreats",
    "a church bell cracked by lightning that now rings only for the rain",
    "a crystal cave where every facet returns a different harmonic to a single note",
    "a spinning prayer courtyard where thousands of feet keep one low drone alive",
    "a lighthouse stair where every seventh step rings softly under the keeper's boot",
    "a great waterfall tuned by a stone lip into one clean deep tone",
    "a pyramid capstone of gold that hums against the sky before a storm",
    "a night desert where the wind draws one enormous standing wave in the sand",
  ],

  /* ---------------- genome · Evolve Med vector 1 ------------------ */
  genome: [
    "a double helix drawn as a braided river of light between two horizons",
    "a genetic circuit rendered as a garden of branching living wires",
    "base pairs shown as interlocking stone bridges across a spiral canyon",
    "a DNA archive: a helix wound onto an ancient spool inside a glass reliquary",
    "a strand of DNA as a railway line with tiny maintenance trains at work",
    "a helix ladder descending into a lit cell like a well of stars",
    "molecular logic gates drawn as tiny stone arches admitting single sparks",
    "a chromosome seen as a tightly wound skein of silver thread in a crystal case",
    "an epigenetic motif shown as a small candle tied to one branch of a helix tree",
    "a genome rendered as a woven tapestry hung in a cathedral of cells",
    "a codon wheel drawn as a rose window of colored light shards",
    "a plasmid ring floating in a cell like a small circular orchard",
    "a cell nucleus as a library where helix scrolls rest in vaulted niches",
    "a helix unwound by a tiny machine, threads drawn taut like a spinning jenny",
    "a genetic river delta where each branch is a different possible trait",
    "a seed cut open to reveal a coiled luminous helix at its heart",
  ],

  /* ---------------- engines · Evolve Med vector 2 ----------------- */
  engines: [
    "a protein folding like an origami crane taking shape from a loose ribbon",
    "an RNA switch shown as a hinge of light opening a tiny gate in a cell wall",
    "a scissor-enzyme gliding along a thread, cutting one precise notch",
    "a nanomachine walker with jointed legs crossing a membrane plain",
    "a proteasome drawn as a barrel vault shredding a ribbon of worn silk",
    "a molecular tweezer joining a broken protein to a recycling furnace",
    "a molecular glue bond shown as a drop of amber joining two drifting gears",
    "a ribosome as a tiny loom knitting a protein ribbon from floating beads",
    "a chaperone protein as a folded paper boat sheltering a new ribbon from waves",
    "a prime editor as a small scribe carving one precise notch into a strand",
    "an enzyme's active site as a lock's keyway fitted by a glowing key",
    "a neoantigen flag flying from a cell tower to summon immune riders",
    "a kinase switch as a railway junction thrown by a single falling bead",
    "a folding funnel drawn as a mountain slope guiding ribbons into valleys",
    "an RNA hairpin as a shepherd's crook hooked over a thread of message",
    "a molecular motor spinning an axle of light inside a ring of stone pillars",
  ],

  /* ---------------- medworld · Evolve Med vector 3 ---------------- */
  medworld: [
    "a lipid nanoparticle as a soap-bubble ferry docking at a cell's harbor wall",
    "a tiny icosahedral shell drawn as a lantern drifting between cells",
    "a bioprinting arm laying down living ink layer by layer into a heart shape",
    "a clinic of the future as a glass greenhouse where patients grow new tissue",
    "a vial production line as a bottling hall of tiny rivers of light",
    "a pharmacokinetic journey drawn as a river running from mountain dose to sea",
    "a senolytic gardener pruning withered lanterns from a tree of cells",
    "a bioprinted organ resting in a glass dome like a blooming coral crown",
    "an intravenous bag as a slow moon feeding its light through a thin tube of stars",
    "a cold-chain caravan of glowing flasks crossing a mountain at night",
    "a hospital ward of transparent pods where wounds close like dawn fog lifting",
    "a longevity orchard where each tree is grafted from older, patient wood",
    "a cell-free factory: ribbons of protein woven in open air by hanging looms",
    "a dose-to-clearance clock drawn as a waterwheel turning a bright stream dim",
    "a mobile clinic wagon as a beacon tent pitched on a distant plain at dusk",
    "an organ transport case opening like a reliquary, light spilling over wings",
  ],

  /* ---------------- interface · Evolve Med vector 4 --------------- */
  interface: [
    "a neural lattice answering a beam of code, filaments lighting in reply",
    "a tissue culture plate as a garden plot where spikes of light sprout in rows",
    "a closed feedback loop drawn as two hands passing a spark around a ring",
    "an electrode array as a harp strung across a petal of living tissue",
    "a metabolic dial turned by a gentle hand of light over a sleeping cell",
    "neural weights and wetware drawn as two flocks of birds merging into one",
    "a chip of glass with a living rime of neurons creeping over its edges",
    "a signals bridge between a mechanical loom and a field of pulsing cells",
    "a dream recorded as dew drops forming along a thread of sleeping axons",
    "a cellular choir rising and falling as a waveform drawn in living threads",
    "a prosthetic branch grafted to a tree, sap rising through both without seam",
    "a cursor of light moving through a meadow of neurons that turn to follow",
    "a membrane rippling as a spoken chord passes through it into the cell",
    "a weaver of code standing at a loom whose threads are living axons",
    "an oscilloscope garden: green waves traced in firefly light over quiet tissue",
    "a handshake between a silicon lattice and a hand of luminous cells",
  ],
};

/** Flat list of generation jobs, in category order. */
export const JOBS = CATEGORY_ORDER.flatMap((category) =>
  subjects[category].map((subject) => ({ category, subject })),
);

export const SUBJECTS = subjects;

/* When run directly, print the job list as JSON to stdout. */
import { pathToFileURL } from "node:url";
const isMain =
  process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  const counts = Object.fromEntries(
    CATEGORY_ORDER.map((c) => [c, subjects[c].length]),
  );
  console.log(JSON.stringify({ total: JOBS.length, counts }, null, 2));
}
