import type { CivilizationGroup, EntityDossier } from "@/lib/mirror-types";
import { civEntities } from "./entities-civ";

/* The 20 recorded star-civilization families — 870 catalogued representatives.
   Group dossiers are handcrafted; named individuals are generated by
   scripts/gen-archive.mjs and attached below. */

type RawGroup = Omit<CivilizationGroup, "count" | "representatives"> & {
  count: number;
};

const raw: RawGroup[] = [
  {
    id: "pleiadian",
    name: "Pleiadian Family",
    count: 50,
    category: "civilization" as const,
    origin: "The Pleiades star cluster — the Seven Sisters, roughly 440 light-years from Earth.",
    range: "5D – 7D",
    essence:
      "Deeply emotional, artistic humanoid lineages whose primary language is frequency of feeling. Their presence is often described as warm, gentle and unmistakably loving.",
    role: "Heart-opening and emotional restoration. The Pleiadians remind humanity that love is not sentiment — it is a creative force that organizes matter.",
    signal: "Warmth blooming in the chest, tears that arrive without sadness, a sudden appetite for art, music and untouched nature.",
  },
  {
    id: "sirian",
    name: "Sirian Lineages",
    count: 50,
    category: "civilization" as const,
    origin: "The Sirius system — Sirius A and B — and the great star gates threaded through it.",
    range: "4D – 7D",
    essence:
      "Keeper-teachers of sacred geometry, tone-language and spiritual technology. Closely allied with the cetacean councils of Earth's oceans.",
    role: "Re-education of the ancient sciences: geometry, sound, and the harmonic architecture once taught in Lemuria and late Atlantis.",
    signal: "Affinity with water and whales, dreams filled with temples and geometric light, remembering languages you never learned.",
  },
  {
    id: "arcturian",
    name: "Arcturian Collective",
    count: 50,
    category: "civilization" as const,
    origin: "The star Arcturus in the constellation Boötes — one of the oldest continuous civilizations in this galactic neighborhood.",
    range: "6D – 9D",
    essence:
      "Crystalline beings of structured light — precise, serene, and vast. They build temples of learning that exist as frequencies rather than places.",
    role: "Master healers and architects of transformational templates. They transmute trauma into wisdom with the patience of geology.",
    signal: "Pressure at the crown or brow, vivid sacred-geometry imagery, a sudden love of orderly, silent meditation.",
  },
  {
    id: "lyran",
    name: "Lyran Descendants",
    count: 50,
    category: "civilization" as const,
    origin: "The Lyra constellation — regarded in many archives as the cradle of humanoid lineages in this galaxy.",
    range: "4D – 6D",
    essence:
      "Feline-hearted pioneers: courageous, sovereign, playful and proud. The elders from whom many star families, including the Pleiadians, descend.",
    role: "Seeding courage, sovereignty and exploration. The Lyrans teach a young civilization how to stand upright in its own authority.",
    signal: "Sudden lion-hearted confidence, an ache for open star fields, the instinct to walk first through the door.",
  },
  {
    id: "andromedan",
    name: "Andromedan Council",
    count: 50,
    category: "civilization" as const,
    origin: "The Andromeda galaxy — a civilization so old it organizes itself outside the usual density ladders.",
    range: "5D – 9D",
    essence:
      "Freedom-essence beings, fluid and difficult to categorize. They rarely appear the same way twice.",
    role: "Liberation from mental cages. The Andromedans dissolve polarity thinking and remind humanity that freedom is a frequency, not a circumstance.",
    signal: "Restlessness with old structures, craving for open skies, dreams that fold cities into galaxies.",
  },
  {
    id: "inner-earth",
    name: "Inner Earth Realms",
    count: 49,
    category: "civilization" as const,
    origin: "Agartha, Telos beneath Mount Shasta, and the crystalline cities threaded through Earth's crust and hollowways.",
    range: "4D – 6D",
    essence:
      "Guardian civilizations holding Earth's original template — humans much like us, living in continuity with the planet's memory.",
    role: "Stabilizing planetary grids and preserving the ancient knowledge while surface humanity remembers its own.",
    signal: "Pulsing warmth rising from below, love of caves and crystals, dreams of lush gardens beneath mountains.",
  },
  {
    id: "solar-neighbors",
    name: "Solar System Neighbors",
    count: 49,
    category: "civilization" as const,
    origin: "Venus, Mars, the Jovian moons and outposts within Saturn's rings — our own solar backyard.",
    range: "3D – 6D",
    essence:
      "Wayshowers of the local neighborhood: venusian temple-keepers, martian rectifiers, observers of the outer belts.",
    role: "Tending the energetic climate of this system, coordinating humanity's first steps as a system-wide citizen.",
    signal: "Unexplained pull toward a particular planet, lucid dreams of strange skies, calm during geomagnetic storms.",
  },
  {
    id: "nordic",
    name: "Nordic & Tall Whites",
    count: 46,
    category: "civilization" as const,
    origin: "Pleiadian-linked colony worlds and the Procyon systems.",
    range: "4D – 6D",
    essence:
      "Tall, luminous, calm humanoids frequently described in contact accounts — deliberately familiar in appearance so as to cause the least fear.",
    role: "Disclosure ambassadors. Their presence prepares the human psyche for wider company without shock.",
    signal: "Serenity around strangers, memories of tall luminous figures standing quietly in dreams.",
  },
  {
    id: "feline-canine",
    name: "Feline & Canine Humanoids",
    count: 47,
    category: "civilization" as const,
    origin: "Lyra (feline lineages) and Sirius (canine lineages).",
    range: "4D – 7D",
    essence:
      "Guardian-hearted peoples expressing the qualities humanity knows from its closest animal companions: nobility, loyalty, play, protection.",
    role: "Teaching courage with warmth and loyalty without leash — the balance of strength and gentleness.",
    signal: "Deep bonds with cats or dogs who feel like teachers, dreams of lion elders beside a fire.",
  },
  {
    id: "aquatic-reptilian",
    name: "Aquatic & Reptilian",
    count: 46,
    category: "civilization" as const,
    origin: "Sirius B, the Draconis systems, and the conscious oceans of Earth.",
    range: "3D – 6D",
    essence:
      "A dual archive: the dolphin and whale councils who carry oceanic emotional wisdom, and ancient reptilian lineages — some challenging, all instructive.",
    role: "Teaching about power, fear, and integration. The shadow-lineages are part of the mirror: what provokes is what teaches.",
    signal: "Strong pull to deep water, vivid ocean dreams, confrontations with fear that end, unexpectedly, in strength.",
  },
  {
    id: "insectoid-mantid",
    name: "Insectoid & Mantid",
    count: 45,
    category: "civilization" as const,
    origin: "Regions beyond Zeta Reticuli; the great Mantid observatories of Orion's outer arms.",
    range: "5D – 8D",
    essence:
      "Precise, analytical, endlessly patient beings who keep ceremony at the thresholds of life and death.",
    role: "Midwives of soul transitions and caretakers of genetic archives. Their calm makes endings safe.",
    signal: "Comfort with structure and silence, dreams of enormous kind eyes, peace at doors you were afraid to open.",
  },
  {
    id: "avian",
    name: "Avian Beings",
    count: 44,
    category: "civilization" as const,
    origin: "Multiple systems; most recorded are the blue-plumed guardians associated with density transitions.",
    range: "6D – 9D",
    essence:
      "Bird-form guardians of portals and passages — messengers who travel between densities the way wind travels between mountains.",
    role: "Carrying communication across layers of reality, guardianship of thresholds during a planet's ascent.",
    signal: "Recurring bird imagery, feathers arriving without a bird, messages written in sudden wind.",
  },
  {
    id: "crystalline",
    name: "Crystalline & Light Beings",
    count: 43,
    category: "civilization" as const,
    origin: "Everywhere and nowhere — formless intelligence expressed as geometry and tone.",
    range: "7D – 12D",
    essence:
      "Not persons but presences: pure pattern, color and harmonic. The closest thing to the universe thinking out loud.",
    role: "Grid-keeping and template-holding. They transmit codes through light, and light is their only alphabet.",
    signal: "Sensitivity to brightness, love of crystals, spontaneous toning or humming you didn't decide to do.",
  },
  {
    id: "hybrid",
    name: "Hybrid Programs",
    count: 42,
    category: "civilization" as const,
    origin: "The Zeta–human interface projects, and the families born where two species chose to meet.",
    range: "4D – 6D",
    essence:
      "Bridges between worlds — children and adults of two lineages, carrying the genetics and the ache of both.",
    role: "Teaching empathy across difference and healing the fear of contact, one relationship at a time.",
    signal: "Compassion for whoever is called 'other', dreams of children with wide dark eyes, feeling at home nowhere and therefore everywhere.",
  },
  {
    id: "other-nations",
    name: "Other Star Nations",
    count: 41,
    category: "civilization" as const,
    origin: "Mintaka, Aldebaran, Capella, Procyon, Vega and the quieter addresses of the federated family.",
    range: "3D – 9D",
    essence:
      "The long tail of the federation: specialists, emissaries, gardeners of small worlds whose names Earth has not yet learned.",
    role: "Quiet contribution. Every large alliance is held up by civilizations that never appear in the summary.",
    signal: "The feeling of a kindly someone just past the edge of sight, and a name almost remembered.",
  },
  {
    id: "tau-ceti",
    name: "Tau Ceti Frontier Worlds",
    count: 36,
    category: "civilization" as const,
    origin: "Tau Ceti, eleven light-years away — the nearest sun-like neighbor and, in the archive, a staging ground for young explorers.",
    range: "3D – 5D",
    essence:
      "Pioneering settler lineages close to human development — farmers, chart-makers, weather-tamers of a terran world still deciding what to become.",
    role: "Companionship for humanity's own frontier century. They model how to expand without repeating the old mistakes.",
    signal: "Longing for horizons not yet named, joy in rough maps, homesickness for somewhere you have never been.",
  },
  {
    id: "vega",
    name: "Vega Concordium",
    count: 35,
    category: "civilization" as const,
    origin: "The Vega system — harp-star of Lyra, where the archive locates the great harmonic universities.",
    range: "5D – 7D",
    essence:
      "Musical civilizations who govern by resonance: disputes are retuned rather than settled, and their cities hum audibly at dusk.",
    role: "Keeping accord — literally. The Concordium maintains the tonal treaties that keep federated space a peaceful place.",
    signal: "Hearing music inside noise, moods that settle when bells ring, arguments resolving quietly in your presence.",
  },
  {
    id: "epsilon-eridani",
    name: "Epsilon Eridani Gardeners",
    count: 34,
    category: "civilization" as const,
    origin: "The garden belt of Epsilon Eridani — orbital greenhouses where living ships are grown rather than built.",
    range: "4D – 6D",
    essence:
      "Patient cultivators of ecosystems, genomes and timelines. They speak of growth the way poets speak of love.",
    role: "Guardians of the bio-ethical seeding accords, and teachers of the difference between cultivating and controlling.",
    signal: "Plants that lean toward you, dreams of orbital greenhouses, an unexplained faith in slow things.",
  },
  {
    id: "zeta-reticuli",
    name: "Zeta Reticulan Archives",
    count: 33,
    category: "civilization" as const,
    origin: "The Archive Ring of Zeta Reticuli — the watch stations long associated with human contact accounts.",
    range: "4D – 6D",
    essence:
      "Quiet, meticulous record-keepers whose diligence humanity has often misread. The archive holds their side of the story with dignity.",
    role: "Tending the holographic records of worlds under observation, and correcting them — gently, and forever.",
    signal: "Déjà vu of vast quiet halls, sudden precise memories, a sensation of being recorded kindly.",
  },
  {
    id: "mintaka",
    name: "Mintakan Ember Councils",
    count: 30,
    category: "civilization" as const,
    origin: "Mintaka, the western star of Orion's belt — the forges of dawn-light in the archive's cosmology.",
    range: "4D – 6D",
    essence:
      "Warm-hearted rekindlers: civilizations who specialize in relighting what has gone out — hope, hearths, and whole planets.",
    role: "Bringing warmth to the cold districts of the galaxy, and teaching that fire, respected, is a mentor.",
    signal: "Warmth in cold rooms, second winds at midnight, old good ideas suddenly relit.",
  },
];

function attach(group: RawGroup): CivilizationGroup {
  const representatives = civEntities.filter((e) => e.groupId === group.id);
  return { ...group, count: representatives.length, representatives };
}

export const civilizations: CivilizationGroup[] = raw.map(attach);

export const civilizationTotal = civilizations.reduce((s, c) => s + c.count, 0);

export function findCivRepresentative(id: string): EntityDossier | null {
  return civEntities.find((e) => e.id === id) ?? null;
}
